# TD Prediction

In this demo we estimate the value function for a given policy using Temporal difference method.

In [1]:
import numpy as np
from gridworld import GridWorld

np.set_printoptions(precision=3,suppress=True)

When we are at state s_t we take an action based on the current observation,we get an reward and move to the next state S_t+1 and also get a new_observation. Using this we look up the value function and compute the reward for state s_t.

In [2]:
def update_value_matrix(value_matrix, observation, new_observation, 
                   reward, alpha, gamma):
    
    u = value_matrix[observation[0], observation[1]]
    u_t1 = value_matrix[new_observation[0], new_observation[1]]
    value_matrix[observation[0], observation[1]] += alpha * (reward + gamma * u_t1 - u)
    return value_matrix

Lets create a gridworld of size (3,4). The terminal states are noted as 1 and others as zero. The agent has four possible actions (UP,DOWN,LEFT,RIGHT) and gets an reward of -0.04 at all states. One of the terminal states has a reward of +1 and other -1 (not favored). Value functions represent how long does it take for an agent to reach the terminal state.

In [3]:
env = GridWorld(3, 4)

#Define the state matrix
state_matrix = np.zeros((3,4))
state_matrix[0, 3] = 1
state_matrix[1, 3] = 1
state_matrix[1, 1] = -1
print("State Matrix:")
print(state_matrix)

State Matrix:
[[ 0.  0.  0.  1.]
 [ 0. -1.  0.  1.]
 [ 0.  0.  0.  0.]]


In [4]:
#Define the reward matrix
reward_matrix = np.full((3,4), -0.04)
reward_matrix[0, 3] = 1
reward_matrix[1, 3] = -1
print("Reward Matrix:")
print(reward_matrix)

Reward Matrix:
[[-0.04 -0.04 -0.04  1.  ]
 [-0.04 -0.04 -0.04 -1.  ]
 [-0.04 -0.04 -0.04 -0.04]]


In [5]:
#Define the transition matrix
transition_matrix = np.array([[0.8, 0.1, 0.0, 0.1],
                              [0.1, 0.8, 0.1, 0.0],
                              [0.0, 0.1, 0.8, 0.1],
                              [0.1, 0.0, 0.1, 0.8]])

#Define the policy matrix
#This is the optimal policy for world with reward=-0.04
policy_matrix = np.array([[1,      1,  1,  -1],
                          [0, np.NaN,  0,  -1],
                          [0,      3,  3,   3]])
print("Policy Matrix:")
print(policy_matrix)

env.setStateMatrix(state_matrix)
env.setRewardMatrix(reward_matrix)
env.setTransitionMatrix(transition_matrix)

value_matrix = np.zeros((3,4))
gamma = 0.999
alpha = 0.1 #constant step size
tot_epoch = 30000
print_epoch = 1000

for epoch in range(tot_epoch):
    #Reset and return the first observation
    observation = env.reset(exploring_starts=True)
    for step in range(1000):
        #Take the action from the action matrix
        action = policy_matrix[observation[0], observation[1]]
        #Move one step in the environment and get obs and reward
        new_observation, reward, done = env.step(action)
        value_matrix = update_value_matrix(value_matrix, observation, 
                                        new_observation, reward, alpha, gamma)
        observation = new_observation
        
        if done: break

    if(epoch % print_epoch == 0):
        print("")
        print("Value matrix after " + str(epoch+1) + " iterations:") 
        print(value_matrix)
#Time to check the value matrix obtained
print("Value matrix after " + str(tot_epoch) + " iterations:")
print(value_matrix)

Policy Matrix:
[[ 1.  1.  1. -1.]
 [ 0. nan  0. -1.]
 [ 0.  3.  3.  3.]]

Value matrix after 1 iterations:
[[-0.004 -0.004  0.1    0.   ]
 [-0.004  0.     0.     0.   ]
 [-0.004 -0.004 -0.004  0.   ]]

Value matrix after 1001 iterations:
[[0.874 0.933 0.987 0.   ]
 [0.826 0.    0.728 0.   ]
 [0.77  0.708 0.664 0.602]]

Value matrix after 2001 iterations:
[[0.884 0.943 0.993 0.   ]
 [0.841 0.    0.847 0.   ]
 [0.759 0.696 0.661 0.469]]

Value matrix after 3001 iterations:
[[0.849 0.91  0.959 0.   ]
 [0.787 0.    0.788 0.   ]
 [0.73  0.698 0.667 0.54 ]]

Value matrix after 4001 iterations:
[[0.825 0.874 0.956 0.   ]
 [0.773 0.    0.527 0.   ]
 [0.728 0.673 0.624 0.212]]

Value matrix after 5001 iterations:
[[0.825 0.874 0.955 0.   ]
 [0.772 0.    0.599 0.   ]
 [0.703 0.663 0.592 0.323]]

Value matrix after 6001 iterations:
[[0.831 0.9   0.966 0.   ]
 [0.767 0.    0.566 0.   ]
 [0.716 0.678 0.631 0.437]]

Value matrix after 7001 iterations:
[[0.835 0.929 0.992 0.   ]
 [0.779 0.    0.666 0